# ================================================================
# DA40 Platform — Windows Setup
# Usage: .\scripts\Setup.ps1
# Requirements: Docker Desktop running
# ================================================================
param(
    [string]$Domain = "",
    [string]$Email  = ""
)

$ErrorActionPreference = "Stop"

function step([string]$n, [string]$msg) {
    Write-Host "`n[$n] $msg" -ForegroundColor Cyan
    Write-Host "    $('─' * ($msg.Length + 4))" -ForegroundColor DarkGray
}
function ok([string]$m)   { Write-Host "    ✓ $m" -ForegroundColor Green  }
function warn([string]$m) { Write-Host "    ! $m" -ForegroundColor Yellow }
function fail([string]$m) { Write-Host "    ✗ $m" -ForegroundColor Red; exit 1 }

# Alphanumeric-only password generator (safe for Docker Compose .env)
function New-Pass([int]$len = 32) {
    $c = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    -join ((1..$len) | ForEach-Object { $c[(Get-Random -Max $c.Length)] })
}

# JWT generator (pure .NET, no external tools needed)
function New-JWT([string]$role, [string]$secret) {
    $iat = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    $exp = $iat + 315360000
    function b64u([string]$s) {
        [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($s)).TrimEnd('=').Replace('+','-').Replace('/','_')
    }
    $h = b64u '{"alg":"HS256","typ":"JWT"}'
    $p = b64u "{`"role`":`"$role`",`"iss`":`"supabase`",`"iat`":$iat,`"exp`":$exp}"
    $d = "$h.$p"
    $hmac = New-Object Security.Cryptography.HMACSHA256
    $hmac.Key = [Text.Encoding]::UTF8.GetBytes($secret)
    $sig = [Convert]::ToBase64String($hmac.ComputeHash([Text.Encoding]::UTF8.GetBytes($d))).TrimEnd('=').Replace('+','-').Replace('/','_')
    "$d.$sig"
}

Clear-Host
Write-Host ""
Write-Host "  ╔══════════════════════════════════════╗" -ForegroundColor Blue
Write-Host "  ║   DA40 PREFLIGHT PLATFORM — SETUP    ║" -ForegroundColor Blue
Write-Host "  ╚══════════════════════════════════════╝" -ForegroundColor Blue
Write-Host ""

# ── Step 1: Check Docker ──────────────────────────────────────
step "1/5" "Checking Docker Desktop"
try {
    docker info 2>&1 | Out-Null
    $v = (docker version --format "{{.Server.Version}}" 2>$null)
    ok "Docker $v is running"
} catch {
    fail "Docker Desktop is not running. Please start it and try again."
}

# ── Step 2: Configuration ─────────────────────────────────────
step "2/5" "Configuration"

if (-not $Domain) {
    $Domain = Read-Host "    Domain (press ENTER for localhost)"
    if (-not $Domain.Trim()) { $Domain = "localhost" }
}
if (-not $Email) {
    $Email = Read-Host "    Your email (will become instructor)"
}

$IsLocal = $Domain -eq "localhost"
$SiteUrl = if ($IsLocal) { "http://localhost" } else { "https://$Domain" }
ok "Site URL: $SiteUrl"

# Generate secrets
$PgPass  = New-Pass 32
$JwtKey  = New-Pass 48
$AnonJwt = New-JWT "anon"         $JwtKey
$SvcJwt  = New-JWT "service_role" $JwtKey

# Write .env with LF line endings (critical for Linux containers)
$lines = @(
    "# DA40 Platform — auto-generated by Setup.ps1",
    "# DO NOT commit this file to git",
    "",
    "SITE_URL=$SiteUrl",
    "POSTGRES_PASSWORD=$PgPass",
    "JWT_SECRET=$JwtKey",
    "ANON_KEY=$AnonJwt",
    "SERVICE_ROLE_KEY=$SvcJwt",
    "",
    "# Email (leave blank to skip confirmation in dev)",
    "SMTP_HOST=",
    "SMTP_PORT=587",
    "SMTP_USER=",
    "SMTP_PASS=",
    "ENABLE_EMAIL_AUTOCONFIRM=true"
)
$utf8lf = New-Object Text.UTF8Encoding $false
[IO.File]::WriteAllLines((Join-Path $PWD ".env"), $lines, $utf8lf)
ok ".env written (alphanumeric passwords, LF line endings)"

# ── Step 3: SSL ───────────────────────────────────────────────
step "3/5" "SSL Certificate"
New-Item -Force -ItemType Directory "nginx\ssl" | Out-Null

if (-not (Test-Path "nginx\ssl\fullchain.pem")) {
    docker run --rm -v "${PWD}\nginx\ssl:/ssl" alpine/openssl `
        req -x509 -nodes -newkey rsa:2048 `
        -keyout /ssl/privkey.pem -out /ssl/fullchain.pem `
        -days 3650 -subj "/CN=$Domain" 2>$null
    ok "Self-signed certificate created (valid 10 years)"
} else {
    ok "Certificate already exists"
}

# ── Step 4: Build & Start ─────────────────────────────────────
step "4/5" "Build & Start"

# Clean old volumes to ensure fresh DB with correct passwords
$hasVolume = docker volume ls --format "{{.Name}}" | Select-String "da40_db_data"
if ($hasVolume) {
    warn "Found existing database volume — removing to apply new passwords"
    docker compose down -v 2>$null
    ok "Old volumes removed"
}

Write-Host "    Building Next.js image (~3 min first time, cached after)..." -ForegroundColor Gray
docker compose build --quiet nextjs
ok "Next.js image built"

Write-Host "    Starting all services..." -ForegroundColor Gray
docker compose up -d
ok "Services started"

# ── Step 5: Wait & Verify ─────────────────────────────────────
step "5/5" "Waiting for services to be ready"

# Wait for postgres
Write-Host "    Postgres..." -ForegroundColor Gray -NoNewline
for ($i = 1; $i -le 40; $i++) {
    $h = docker inspect da40_postgres --format "{{.State.Health.Status}}" 2>$null
    if ($h -eq "healthy") { Write-Host " ready" -ForegroundColor Green; break }
    Write-Host "." -NoNewline -ForegroundColor DarkGray
    Start-Sleep 3
    if ($i -eq 40) { fail "Postgres did not start. Run: docker compose logs postgres" }
}

# Wait for db migration sidecar (must exit with code 0)
Write-Host "    DB migration..." -ForegroundColor Gray -NoNewline
for ($i = 1; $i -le 40; $i++) {
    $state = docker inspect da40_db_migrate --format "{{.State.Status}}" 2>$null
    $exitCode = docker inspect da40_db_migrate --format "{{.State.ExitCode}}" 2>$null
    if ($state -eq "exited" -and $exitCode -eq "0") {
        Write-Host " done" -ForegroundColor Green
        break
    }
    Write-Host "." -NoNewline -ForegroundColor DarkGray
    Start-Sleep 2
    if ($i -eq 40) { fail "DB migration failed. Run: docker compose logs db_migrate" }
}

# Wait for auth API endpoint
Write-Host "    GoTrue auth..." -ForegroundColor Gray -NoNewline
for ($i = 1; $i -le 30; $i++) {
    try {
        $r = Invoke-WebRequest "http://localhost/api/auth/v1/health" -UseBasicParsing -TimeoutSec 5
        if ($r.StatusCode -eq 200) {
            Write-Host " ready" -ForegroundColor Green
            break
        }
    } catch { }
    Write-Host "." -NoNewline -ForegroundColor DarkGray
    Start-Sleep 2
    if ($i -eq 30) { fail "GoTrue API did not become ready. Run: docker compose logs gotrue" }
}

ok "Auth API responding"

# ── Done ──────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ╔══════════════════════════════════════╗" -ForegroundColor Green
Write-Host "  ║        PLATFORM IS READY! 🚀          ║" -ForegroundColor Green
Write-Host "  ╚══════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  URL:     $SiteUrl" -ForegroundColor White
Write-Host "  Email:   $Email" -ForegroundColor White
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor Cyan
Write-Host "  1. Open $SiteUrl/auth/register in your browser"
Write-Host "  2. Create an account with: $Email"
Write-Host "  3. Run: .\scripts\set-instructor.ps1 -Email $Email"
Write-Host ""
Write-Host "  Useful commands:" -ForegroundColor DarkGray
Write-Host "  docker compose ps              # check status"
Write-Host "  docker compose logs -f         # live logs"
Write-Host "  docker compose logs gotrue     # auth logs"
Write-Host "  docker compose down -v         # full reset"
Write-Host "  .\scripts\backup.ps1           # backup database"
Write-Host ""
