#!/usr/bin/env bash
# ================================================================
# DA40 Platform — Linux/Mac Setup
# Usage: bash scripts/setup.sh [domain] [email]
# ================================================================
set -euo pipefail

DOMAIN="${1:-localhost}"
EMAIL="${2:-}"
SITE_URL="http://localhost"
[ "$DOMAIN" != "localhost" ] && SITE_URL="https://${DOMAIN}"

blue()  { echo -e "\033[34m$*\033[0m"; }
green() { echo -e "\033[32m  ✓ $*\033[0m"; }
warn()  { echo -e "\033[33m  ! $*\033[0m"; }
step()  { echo -e "\n\033[36m[$1] $2\033[0m"; echo "    $(printf '─%.0s' $(seq 1 $((${#2}+4))))"; }

# Alphanumeric password (safe for Docker Compose .env)
alphanum() { LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c "${1:-32}"; }

# JWT generator
gen_jwt() {
    local ROLE="$1" SECRET="$2"
    python3 - <<PY
import hmac, hashlib, base64, json, time
secret = "$SECRET"
iat    = int(time.time())
exp    = iat + 315360000
def b64u(s):
    b = s.encode() if isinstance(s,str) else s
    return base64.urlsafe_b64encode(b).rstrip(b'=').decode()
h = b64u(json.dumps({"alg":"HS256","typ":"JWT"},separators=(',',':')))
p = b64u(json.dumps({"role":"$ROLE","iss":"supabase","iat":iat,"exp":exp},separators=(',',':')))
d = f"{h}.{p}"
sig = b64u(hmac.new(secret.encode(), d.encode(), hashlib.sha256).digest())
print(f"{d}.{sig}")
PY
}

clear
blue "
  ╔══════════════════════════════════════╗
  ║   DA40 PREFLIGHT PLATFORM — SETUP    ║
  ╚══════════════════════════════════════╝"

# ── Step 1: Docker ────────────────────────────────────────────
step "1/5" "Checking Docker"
if ! docker info &>/dev/null; then
    echo "  ✗ Docker is not running. Please start Docker and retry."
    exit 1
fi
green "Docker $(docker version --format '{{.Server.Version}}') running"

# ── Step 2: Configuration ─────────────────────────────────────
step "2/5" "Configuration"

if [ -z "$EMAIL" ]; then
    read -r -p "    Your email (will become instructor): " EMAIL
fi
green "Site URL: $SITE_URL"

PG_PASS=$(alphanum 32)
JWT_KEY=$(alphanum 48)
ANON_JWT=$(gen_jwt "anon" "$JWT_KEY")
SVC_JWT=$(gen_jwt "service_role" "$JWT_KEY")

# Write .env
cat > .env << ENVEOF
# DA40 Platform — auto-generated by setup.sh
# DO NOT commit this file to git

SITE_URL=${SITE_URL}
POSTGRES_PASSWORD=${PG_PASS}
JWT_SECRET=${JWT_KEY}
ANON_KEY=${ANON_JWT}
SERVICE_ROLE_KEY=${SVC_JWT}

SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
ENABLE_EMAIL_AUTOCONFIRM=true
ENVEOF
green ".env written"

# ── Step 3: SSL ───────────────────────────────────────────────
step "3/5" "SSL Certificate"
mkdir -p nginx/ssl
if [ ! -f nginx/ssl/fullchain.pem ]; then
    openssl req -x509 -nodes -newkey rsa:2048 \
        -keyout nginx/ssl/privkey.pem \
        -out    nginx/ssl/fullchain.pem \
        -days 3650 -subj "/CN=${DOMAIN}" 2>/dev/null
    green "Self-signed certificate created"
else
    green "Certificate already exists"
fi

# ── Step 4: Build & Start ─────────────────────────────────────
step "4/5" "Build & Start"

# Remove old volumes if they exist (ensures fresh DB)
if docker volume ls --format "{{.Name}}" | grep -q "da40_db_data"; then
    warn "Removing existing database volume to apply new passwords"
    docker compose down -v 2>/dev/null || true
fi

echo "    Building Next.js image (~3 min first time)..."
docker compose build --quiet nextjs
green "Next.js image built"

docker compose up -d
green "Services started"

# ── Step 5: Wait ──────────────────────────────────────────────
step "5/5" "Waiting for services"

printf "    Postgres"
for i in $(seq 1 40); do
    h=$(docker inspect da40_postgres --format '{{.State.Health.Status}}' 2>/dev/null || echo "starting")
    [ "$h" = "healthy" ] && echo " ✓" && break
    printf "."
    sleep 3
    [ "$i" -eq 40 ] && echo "" && echo "  ✗ Postgres timeout. Run: docker compose logs postgres" && exit 1
done

printf "    DB migration"
for i in $(seq 1 40); do
    state=$(docker inspect da40_db_migrate --format '{{.State.Status}}' 2>/dev/null || echo "missing")
    code=$(docker inspect da40_db_migrate --format '{{.State.ExitCode}}' 2>/dev/null || echo "1")
    if [ "$state" = "exited" ] && [ "$code" = "0" ]; then
        echo " ✓"
        break
    fi
    printf "."
    sleep 2
    [ "$i" -eq 40 ] && echo "" && echo "  ✗ DB migration failed. Run: docker compose logs db_migrate" && exit 1
done

printf "    GoTrue auth"
for i in $(seq 1 30); do
    if curl -sf http://localhost/api/auth/v1/health | grep -q ok; then
        echo " ✓"
        break
    fi
    printf "."
    sleep 2
    [ "$i" -eq 30 ] && echo "" && echo "  ✗ GoTrue API not ready. Run: docker compose logs gotrue" && exit 1
done

green "Auth API responding"

echo ""
blue "
  ╔══════════════════════════════════════╗
  ║        PLATFORM IS READY! 🚀          ║
  ╚══════════════════════════════════════╝"
echo ""
echo "  URL:   ${SITE_URL}"
echo "  Email: ${EMAIL}"
echo ""
echo "  Next steps:"
echo "  1. Open ${SITE_URL}/auth/register"
echo "  2. Create account with: ${EMAIL}"
echo "  3. bash scripts/set-instructor.sh ${EMAIL}"
echo ""
echo "  Commands:"
echo "  docker compose ps              # status"
echo "  docker compose logs -f         # live logs"
echo "  docker compose down -v         # full reset"
echo "  bash scripts/backup.sh         # backup"
echo ""
